apiVersion: v2
name: kubevirt-standalone-cp
description: |
  A KCM template to deploy a k0s cluster on KubeVirt with bootstrapped control plane nodes.
type: application
version: 1.4.0
appVersion: "v1.31.3+k0s.1"
annotations:
  cluster.x-k8s.io/provider: infrastructure-kubevirt, control-plane-k0sproject-k0smotron, bootstrap-k0sproject-k0smotron
  k0rdent.mirantis.com/type: deployment
  cluster.x-k8s.io/bootstrap-k0sproject-k0smotron: v1beta1
  cluster.x-k8s.io/control-plane-k0sproject-k0smotron: v1beta1
  cluster.x-k8s.io/infrastructure-kubevirt: v1beta1
